lists/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='list'),
    path('update_list/<str:pk>', views.updateList, name='update_list'),
    path('delete/<str:pk>', views.deleteList, name='delete'),
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('lists.urls')),
]

lists/models.py
from django.db import models

# Create your models here.

PRIORITY_CHOICES = (
    ('high','High'),
    ('medium','Medium'),
    ('low','Low'),
)

class List(models.Model):
    title = models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    list_date = models.DateTimeField(auto_now_add=True)
    priority = models.CharField(max_length=6, choices=PRIORITY_CHOICES, default='medium')

    def __str__(self):
        return self.title

lists/forms.py
from django import forms
from django.forms import ModelForm

from .models import *

class ListForm(forms.ModelForm):

    title = forms.CharField(widget= forms.TextInput(attrs={'placeholder':'Add new item...'}))

    class Meta:
        model = List
        fields = '__all__'

  

lists/views.py
from django.shortcuts import render, redirect

from .models import *
from .forms import *

# Create your views here.
def index(request):
    lists = List.objects.all()
    form = ListForm()

    if request.method == 'POST':
        form = ListForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/')

    context = {
        'lists': lists,
        'form': form,
    }
    
    return render(request, 'lists/index.html', context)


def updateList(request, pk):
    list = List.objects.get(id=pk)

    form = ListForm(instance=list)

    if request.method == 'POST':
        form = ListForm(request.POST, instance=list)
        if form.is_valid:
            form.save()
            return redirect('/')

    context = {
        'form':form,
    }

    return render(request, 'lists/update_list.html', context)


def deleteList(request, pk):
    item = List.objects.get(id=pk)

    if request.method == 'POST':
        item.delete()
        return redirect('/')

    context = {
        'item':item,
    }

    return render(request, 'lists/delete.html', context)

templates/lists/delete.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/style.css' %}">



<div class="center-column">
    <p class="text-center"> Are you sure you want to delete <strong>{{ item }}</strong> ??</p>
    
        <a class="btn btn-sm btn-info w" href="{% url 'list' %}">Cancel</a>
    
        <form method="POST" action="">
            {% csrf_token %}
            <input class="btn btn-sm btn-danger" type="submit" value="Confirm">
        </form> 
       
</div>
   

templates/lists/index.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<title>Cheat Day List</title>

<div class="center-column">
    
    <form method="POST" action="/">
        {% csrf_token %}
        
            {{ form.title }}
            {{ form.priority }}

        <input class="btn btn-info" type="submit" name="Create List" value="Add">
    </form>

    {% if lists %}
        {% for list in lists %}
            <div class="item-row">
                
                <a class="btn btn-sm btn-info" href="{% url 'update_list' list.id %}">Update</a>
                <a class="btn btn-sm btn-danger" href="{% url 'delete' list.id %}">Delete</a>
                
                {% if list.complete == True %}
                    <strike>{{ list.title }}</strike>
                {% else %}
                    <span>{{ list.title }}</span>
                {% endif %}
                <div class="dark float-right">
                    {{list.priority}}
                </div>
                
            </div>
        {% endfor %}
    {% else %}
        <h2>Add a list</h2>
    {% endif %}

    

</div>

templates/lists/update_list.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<div class="center-column">
    <h3>Update List</h3>
    <div class="">
        <form method="POST" action="">
            {% csrf_token %}
            {{form.title}} 
            <div id="id_complete">
               <span>Complete </span> {{form.complete}}    
            </div>                                             
            {{form.priority}}                  
            <input class="btn btn-info " type="submit" name="Update List" value="Update">
        </form>
    </div>
    
</div>
    